---
title: "Publications"
---

You can [email](mailto:dkrichards@unm.edu) me for a PDF of any of my publications.

## In Press

1.  Pfund, R. A., **Richards, D. K.**, Boness, C. L., Schwebel, F. J., Tonigan, J. S., Maisto, S. A., & Witkiewitz, K. (in press). Relative and interactive associations of psychotherapy and Alcoholics Anonymous attendance with alcohol use disorder outcomes. *Journal of Studies on Alcohol and Drugs*.

## 2022

2.  López, C. I., **Richards, D. K.**, & Field, C. A. (2022). Perceived discrimination and alcohol-related problems among Hispanic college students: The protective role of serious harm reduction behaviors. *Journal of Ethnicity in Substance Abuse*, *21*(1), 272-283. \[[DOI](https://doi.org/10.1080/15332640.2020.1747040)\]

3.  Pearson, M. R., Schwebel, F. J., R**ichards, D. K.**, & Witkiewitz, K. (2022). Examining replicability in addictions research: How to assess and ways forward. *Psychology of Addictive Behaviors*, *36*(3), 260-270. \[[DOI](https://psycnet.apa.org/doi/10.1037/adb0000730)\]

4.  **Richards, D. K.**, Schwebel, F. J., Cowie, K. D., Pearson, M. R., & Witkiewitz, K. (2022). Measurement invariance of the University of Rhode Island Change Assessment Scale in Project MATCH: An exploratory structural equation modeling approach. *Alcoholism: Clinical and Experimental Research*. Advance online publication. \[[DOI](https://doi.org/10.1111/acer.14849)\]

5.  **Richards, D. K.**, Schwebel, F. J., Joseph, V. W., & Pearson, M. R. (2022). A comprehensive examination of motivational profiles for alcohol-related behaviors among college students. *Experimental and Clinical Psychopharmacology*. Advance online publication. \[[DOI](https://psycnet.apa.org/doi/10.1037/pha0000605)\]

6.  **Richards, D. K.**, Schwebel, F. J., Pearson, M. R., & Study Team, P. S. (2022). A test of interaction effects between cannabis protective behavioral strategies and antecedents of cannabis-related consequences. *Journal of Psychoactive Drugs*, *54*(1), 61-69. \[[DOI](https://doi.org/10.1080/02791072.2021.1909188)\]

7.  Schwebel, F. J., **Richards, D. K.**, Pfund, R. A., Joseph, V. W., Pearson, M. R., & Marijuana Outcomes Study Team. (2022). Using Decision Trees to Identify Salient Predictors of Cannabis-Related Outcomes. *Journal of Psychoactive Drugs*. Advance online publication. \[[DOI](https://doi.org/10.1080/02791072.2021.2014081)\]

8.  Schwebel, F. J., Weinstein, A. P., **Richards, D. K.**, Bravo, A. J., & Pearson, M. R. (2022). Examining cross-country and sex differences on a comprehensive assessment of protective behavioral strategies for alcohol. *Substance Use & Misuse*, *57*(1), 47-56. \[[DOI](https://doi.org/10.1080/10826084.2021.1990330)\]

## 2021

9.  Alvarez, M. J., **Richards, D. K.**, Ramirez, S. O., & Field, C. A. (2021). Social network heavy drinking moderates the effects of a brief motivational intervention for alcohol use among injured patients. *Addictive Behaviors*, *112*, 106594. \[[DOI](https://doi.org/10.1016/j.addbeh.2020.106594)\]

10. Montes, K. S., **Richards, D. K.**, Pearson, M. R., & Marijuana Outcomes Study Team. (2021). A novel approach to assess descriptive and injunctive norms for college student marijuana use. *Addictive Behaviors*, *117*, 106755. \[[DOI](https://doi.org/10.1016/j.addbeh.2020.106755)\]

11. Pearson, M. R., Wilson, A. D., **Richards, D. K.**, & Witkiewitz, K. (2021). Reconsidering alcohol treatment non-responders: psychosocial functioning among heavy drinkers 3 years following treatment. *Addiction*, *116*(5), 1262-1269. \[[DOI](https://doi.org/10.1111/add.15280)\]

12. **Richards, D. K.**, Fetterman, A. K., Krebs, M. C., Neugebauer, J., Ray, D. G., & Sassenberg, K. (2021). Positive and negative emotions predict weight loss intentions and behaviors beyond theory of planned behavior constructs. *Eating and Weight Disorders-Studies on Anorexia, Bulimia and Obesity*, *26*(3), 829-838. \[[DOI](https://doi.org/10.1007/s40519-020-00917-4)\]

13. **Richards, D. K.**, Morera, O. F., & Field, C. A. (2021). The psychometric properties of a version of the Treatment Self-Regulation Questionnaire for assessing motivations for responsible drinking. *Journal of American College Health*, *69*(7), 742-749. \[[DOI](https://doi.org/10.1080/07448481.2019.1706536)\]

14. **Richards, D. K.**, Morera, O. F., Schwebel, F. J., Pearson, M. R., & Field, C. A. (2021). Measurement Invariance of the Readiness to Change Questionnaire Among Injured Patients Who Received a Brief Intervention for Alcohol Use. *Assessment*. Advance online publication. \[[DOI](https://doi.org/10.1177/10731911211040106)\]

15. **Richards, D. K.**, Pearson, M. R., & Field, C. A. (2021). Further validation of the Treatment Self-Regulation Questionnaire for assessing motivations for responsible drinking: A test of self-determination theory. *Experimental and Clinical Psychopharmacology*, *29*(6), 679-688. \[[DOI](https://psycnet.apa.org/doi/10.1037/pha0000405)\]

16. **Richards, D. K.**, Pearson, M. R., & Field, C. A. (2021). A comprehensive examination of alcohol-related motivations among college students: Unique relations of drinking motives and motivations for drinking responsibly. *Experimental and Clinical Psychopharmacology*. Advance online publication. \[[DOI](https://psycnet.apa.org/doi/10.1037/pha0000526)\]

17. **Richards, D. K.**, Pearson, M. R., Hallgren, K. A., Heather, N., & Witkiewitz, K. (2021). An application of moderated nonlinear factor analysis to develop a commensurate measure of alcohol problems across four alcohol treatment studies. *Drug and Alcohol Dependence*, *229*, 109068. \[[DOI](https://doi.org/10.1016/j.drugalcdep.2021.109068)\]

18. **Richards, D. K.**, Pearson, M. R., & Witkiewitz, K. (2021). Understanding alcohol harm reduction behaviors from the perspective of self-determination theory: a research agenda. *Addiction Research & Theory*, *29*(5), 392-397. \[[DOI](https://doi.org/10.1080/16066359.2020.1863378)\]

19. R**ichards, D. K.**, Schwebel, F. J., Bravo, A. J., Pearson, M. R., & Cross-Cultural Addictions Study Team. (2021). A comparison of cannabis protective behavioral strategies use across cultures and sex. *Addictive Behaviors*, *120*, 106966. \[[DOI](https://doi.org/10.1016/j.addbeh.2021.106966)\]

20. **Richards, D. K.**, Schwebel, F. J., Sotelo, M., & Pearson, M. R. (2021). Self-reported symptoms of cannabis use disorder: Psychometric testing and validation. *Experimental and Clinical Psychopharmacology*, *29*(2), 157-165. \[[DOI](https://psycnet.apa.org/doi/10.1037/pha0000455)\]

21. Schwebel, F. J., **Richards, D. K.**, Pearson, M. R., & Protective Strategies Study Team. (2021). A test of interaction effects between alcohol protective behavioral strategies and antecedents of alcohol-related consequences. *Addictive Behaviors*, *114*, 106707. \[[DOI](https://doi.org/10.1016/j.addbeh.2020.106707)\]

## 2020

22. Curtis, S. R., **Richards, D. K.**, & Jones, D. N. (2020). The Association between Psychopathy and Influencing Others to Use Substances. *Substance Use & Misuse*, *55*(7), 1097-1105. \[[DOI](https://doi.org/10.1080/10826084.2020.1729196)\]

23. Field, C. A., **Richards, D. K.**, Castro, Y., Alonso Cabriales, J., Wagler, A., & von Sternberg, K. (2020). The Effects of a Brief Motivational Intervention for Alcohol Use through Stages of Change among Nontreatment Seeking Injured Patients. *Alcoholism: Clinical and Experimental Research*, *44*(11), 2361-2372. \[[DOI](https://doi.org/10.1111/acer.14466)\]

24. Lloyd, C. D., Hanson, R. K., **Richards, D. K.**, & Serin, R. C. (2020). Reassessment improves prediction of criminal recidivism: A prospective study of 3,421 individuals in New Zealand. *Psychological Assessment*, *32*(6), 568-581. \[[DOI](https://doi.org/10.1037/pas0000813)\]

25. **Richards, D. K.**, Morera, O. F., Cabriales, J. A., Smith, J. C., & Field, C. A. (2020). Factor, concurrent and predictive validity of the Readiness to Change Questionnaire \[Treatment Version\] among non-treatment-seeking individuals. *Alcohol and Alcoholism*, *55*(4), 409-415. \[[DOI](https://doi.org/10.1093/alcalc/agaa021)\]

26. **Richards, D. K.**, Pearson, M. R., & Field, C. A. (2020). Profiles of motivations for responsible drinking among college students: A self-determination theory perspective. *Addictive Behaviors*, *111*, 106550. \[[DOI](https://doi.org/10.1016/j.addbeh.2020.106550)\]

## 2019

27. Cabriales, J. A., **Richards, D. K.**, & Cooper, T. V. (2019). Heterogeneity of intermittent smokers in a Hispanic college student sample. *Addictive Behaviors*, *96*, 94-99. \[[DOI](https://doi.org/10.1016/j.addbeh.2019.04.028)\]

28. **Richards, D. K.**, Pearson, M. R., Morera, O. F., & Field, C. A. (2019). Protective behavioral strategies predict alcohol-related problems among injured patients following a brief intervention. *Drug and Alcohol Dependence*, *205*, 107535. \[[DOI](https://doi.org/10.1016/j.drugalcdep.2019.06.037)\]

## 2018

29. **Richards, D. K.**, Puentes, R. P., Gonzales, R., Smith, J. C., Field, C. A., & Morera, O. F. (2018). A psychometric evaluation of the Protective Behavioral Strategies Scale-20 among internet samples of adult drinkers. *Addictive Behaviors Reports*, *8*, 71-78. \[[DOI](https://doi.org/10.1016/j.abrep.2018.08.002) [PDF](Richards2018_PBSS20_Adults.pdf)\]

30. Riskind, J. H., & **Richards, D. K.** (2018). The effect of germ movement on the construal of mental states in germs: The moderating role of contamination fear. *Cognitive Therapy and Research*, *42*(1), 36-47. \[[DOI](https://doi.org/10.1007/s10608-017-9877-2)\]
